version: 2

submodules:
  include: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    nodejs: "17"

python:
  install:
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .
  jobs:
    post_install:
      - python build.py
