version: 2

submodules:
  include: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    nodejs: "16"
  jobs:
    pre_install:
      - python build.py

python:
  install:
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: prod_conf.py
