[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = true

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]
