name: build wheels

on:
  push

jobs:
  
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout the repository and submodules      
      uses: actions/checkout@v3
      with:
        submodules: true        

    - name: Run cibuildwheel
      uses: pypa/cibuildwheel@v2.11.4
      # env:
      #   CIBW_SOME_OPTION: value
      #    ...
      # with:
      #   package-dir: .
      #   output-dir: wheelhouse
      #   config-file: "{package}/pyproject.toml"

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
