name: publish

on:
  workflow_dispatch

jobs:

  publish:
    runs-on: ${{ matrix.os }}-latest
    env:
      PYTEST_ADDOPTS: "--color=yes"
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.10']
    steps:
    - name: Checkout the repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        pipx install poetry
        poetry config virtualenvs.prefer-active-python true

    - name: Install rsm-markup
      run: |
        poetry update
        poetry install --with dev
        poetry show

    - name: Build
      run: |
        poetry build

    - name: Run test suite
      run: |
        poetry run pytest -vv && poetry run pytest -vv --doctest-modules rsm && cd docs && poetry run make doctest

    - name: Publish
      run: |
        poetry publish --dry-run --skip-existing
